#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"
echo "-----> Installing Newrelic ..."

DIR=/app

COMMAND=$(cat <<EOF
export DEBIAN_FRONTEND=noninteractive

echo "-----> NewRelic anabled status in ENV: \$NEW_RELIC_ENABLED"
echo "-----> License in ENV: \$NEW_RELIC_LICENSE_KEY"
echo "-----> App Name in ENV: \$NEW_RELIC_APP_NAME"

sleep 1 # wait so that docker run has not exited before docker attach
EOF
)

id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
